version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.31
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=MyNewPass4!
      - MYSQL_DATABASE=opensips
      - MYSQL_USER=opensips
      - MYSQL_PASSWORD=Opensipsrw4!
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    networks:
      sipnetwork:
        ipv4_address: 192.168.1.100
    volumes:
      - $PWD/mysql/data:/var/lib/mysql
      - $PWD/mysql/config:/etc/mysql/conf.d
      - $PWD/mysql/init:/docker-entrypoint-initdb.d
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
  redis:
    container_name: redis
    image: redis:7.0
    restart: always
    command: redis-server --appendonly yes --requirepass foo2HsFDSa
    volumes:
      - $PWD/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      sipnetwork:
        ipv4_address: 192.168.1.103
  mongo:
    container_name: mongo
    image: mongo:4.1
    privileged: true
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Opensipsrw4!
      - MONGO_INITDB_DATABASE=opensips
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/mongodb/setup/:/docker-entrypoint-initdb.d/
      - $PWD/mongodb/data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --bind_ip 0.0.0.0 --auth --wiredTigerCacheSizeGB 2
    networks:
      sipnetwork:
        ipv4_address: 192.168.1.104
networks:
  sipnetwork:
    external:
      name: sipnet
